package de.alphaloop.chronos.backend.dto.request;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

// ═══════════════════════════════════════════════════════════════════════════
// WHY JAVA RECORDS FOR REQUEST DTOs?
//
// Records (Java 16+) are ideal for incoming data:
//   - Immutable: once created from JSON, fields cannot change
//   - Compact: no boilerplate getters/setters/constructors
//   - Auto-generated: equals, hashCode, toString for free
//   - Explicit contract: the record declaration IS the documentation
//
// WHY SEPARATE REQUEST AND RESPONSE DTOs?
//
// One DTO for both directions seems tempting (less code), but leads to problems:
//
//   Request needs: @NotBlank @Email validation annotations
//   Response needs: id, createdAt, updatedAt (fields that come FROM the DB)
//
//   If you mix them: validation annotations on id (never makes sense),
//   or exposing password_hash in responses (security disaster).
//
// Strict separation: Request = "what we accept", Response = "what we return".
// The mapper bridges the gap between Request → Entity → Response.
//
// WHY NOT USE THE ENTITY DIRECTLY AS A REQUEST BODY?
//
// @RestController
// public ResponseEntity<Customer> create(@RequestBody Customer customer) { ... }
// ↑ THIS IS WRONG. Reasons:
//
// 1. SECURITY: the client could set customer.id, customer.active = true,
//    inject any field Jackson can deserialize — including internal fields.
//    @JsonIgnore helps but is error-prone (forget one field → vulnerability).
//
// 2. VALIDATION LEAKAGE: JPA annotations (@Column nullable=false) are not
//    validation. They fail at the DB level (cryptic ConstraintViolationException),
//    not at the controller level (clean 400 Bad Request with field errors).
//    Request DTOs carry Jakarta Validation annotations (@NotBlank, @Email)
//    that fire before any business logic runs.
//
// 3. COUPLING: if the entity changes (add a field, rename), the API changes too.
//    DTO is a stable API contract independent of the internal model.
// ═══════════════════════════════════════════════════════════════════════════


// ─── CUSTOMER ───────────────────────────────────────────────────────────────

/**
 * Request DTO for creating a new customer.
 * <p>
 * Only the fields the CLIENT provides. No id (generated by DB),
 * no active (always true on creation), no createdAt (set by auditing).
 *
 * @NotBlank: rejects null AND empty strings AND strings with only whitespace.
 * Difference from @NotNull: @NotNull accepts " " (a space), @NotBlank does not.
 * For name/email fields, a blank string is as useless as null — use @NotBlank.
 */
public record CustomerCreateRequest(

        @NotBlank(message = "Customer name is required")
        @Size(max = 255, message = "Name must not exceed 255 characters")
        String name,

        @NotBlank(message = "Email is required")
        @Email(message = "Email must be a valid email address")
        @Size(max = 255)
        String email,

        @Size(max = 50, message = "Phone number must not exceed 50 characters")
        String phone  // nullable — phone is optional in the domain model

) {
}